"use client";

import { CheckCircle2, XCircle, AlertTriangle, Leaf, Percent, FlaskConical, RotateCcw } from "lucide-react";

export interface AnalysisResult {
    diseaseName: string;
    diseaseSpreadPercent: number;
    qualityStatus: "High Quality" | "Medium Quality" | "Rejected";
    healthyTissuePercent: number;
    maskImageUrl?: string;
}

interface Props {
    result: AnalysisResult;
    originalImage: string;
    onReset: () => void;
}

const statusConfig = {
    "High Quality": {
        icon: <CheckCircle2 className="h-5 w-5" />,
        color: "text-emerald-600 dark:text-emerald-400",
        bg: "bg-emerald-50 dark:bg-emerald-900/30",
        border: "border-emerald-200 dark:border-emerald-800",
        bar: "bg-emerald-500",
        badge: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300",
    },
    "Medium Quality": {
        icon: <AlertTriangle className="h-5 w-5" />,
        color: "text-amber-600 dark:text-amber-400",
        bg: "bg-amber-50 dark:bg-amber-900/20",
        border: "border-amber-200 dark:border-amber-800",
        bar: "bg-amber-400",
        badge: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
    },
    "Rejected": {
        icon: <XCircle className="h-5 w-5" />,
        color: "text-red-600 dark:text-red-400",
        bg: "bg-red-50 dark:bg-red-900/20",
        border: "border-red-200 dark:border-red-800",
        bar: "bg-red-500",
        badge: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300",
    },
};

export default function ResultDisplay({ result, originalImage, onReset }: Props) {
    const config = statusConfig[result.qualityStatus];

    return (
        <div className="flex flex-col gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Status Banner */}
            <div className={`flex items-center gap-3 rounded-xl border p-4 ${config.bg} ${config.border}`}>
                <span className={config.color}>{config.icon}</span>
                <div>
                    <p className={`font-bold text-lg ${config.color}`}>{result.qualityStatus}</p>
                    <p className="text-sm text-zinc-600 dark:text-zinc-400">
                        {result.qualityStatus === "High Quality"
                            ? "This leaf meets the medical grade threshold and is suitable for production."
                            : result.qualityStatus === "Medium Quality"
                                ? "Partially affected. Use with caution or blend with healthier stock."
                                : "Disease spread exceeds acceptable limits. Reject from medicinal production."}
                    </p>
                </div>
            </div>

            {/* Images */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="flex flex-col gap-2">
                    <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Original Image</p>
                    <div className="overflow-hidden rounded-xl border border-zinc-200 dark:border-zinc-800">
                        <img src={originalImage} alt="Original leaf" className="w-full object-cover aspect-square" />
                    </div>
                </div>
                <div className="flex flex-col gap-2">
                    <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Disease Mask</p>
                    <div className="relative overflow-hidden rounded-xl border border-zinc-200 dark:border-zinc-800 aspect-square bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center">
                        {result.maskImageUrl ? (
                            <img src={result.maskImageUrl} alt="Disease mask" className="w-full h-full object-cover" />
                        ) : (
                            <div className="text-center px-4">
                                <FlaskConical className="mx-auto h-8 w-8 text-zinc-400 mb-2" />
                                <p className="text-xs text-zinc-400">Mask generated by U-Net model</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Metrics */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                {/* Disease Name */}
                <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
                    <div className="flex items-center gap-2 text-zinc-500 dark:text-zinc-400">
                        <Leaf className="h-4 w-4" />
                        <span className="text-xs font-semibold uppercase tracking-wider">Disease</span>
                    </div>
                    <p className="text-xl font-bold capitalize text-zinc-900 dark:text-zinc-100">
                        {result.diseaseName}
                    </p>
                </div>

                {/* Spread */}
                <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
                    <div className="flex items-center gap-2 text-zinc-500 dark:text-zinc-400">
                        <Percent className="h-4 w-4" />
                        <span className="text-xs font-semibold uppercase tracking-wider">Disease Spread</span>
                    </div>
                    <p className="text-xl font-bold text-zinc-900 dark:text-zinc-100">
                        {result.diseaseSpreadPercent.toFixed(1)}%
                    </p>
                    <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800">
                        <div
                            className={`h-full rounded-full transition-all duration-700 ${config.bar}`}
                            style={{ width: `${result.diseaseSpreadPercent}%` }}
                        />
                    </div>
                </div>

                {/* Healthy */}
                <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
                    <div className="flex items-center gap-2 text-zinc-500 dark:text-zinc-400">
                        <CheckCircle2 className="h-4 w-4" />
                        <span className="text-xs font-semibold uppercase tracking-wider">Healthy Tissue</span>
                    </div>
                    <p className="text-xl font-bold text-zinc-900 dark:text-zinc-100">
                        {result.healthyTissuePercent.toFixed(1)}%
                    </p>
                    <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800">
                        <div
                            className="h-full rounded-full bg-emerald-500 transition-all duration-700"
                            style={{ width: `${result.healthyTissuePercent}%` }}
                        />
                    </div>
                </div>
            </div>

            {/* Quality badge */}
            <div className={`inline-flex items-center gap-2 self-start rounded-full px-4 py-2 text-sm font-semibold ${config.badge}`}>
                {config.icon}
                Medicinal Quality Grade: {result.qualityStatus}
            </div>

            {/* Reset */}
            <button
                onClick={onReset}
                className="flex items-center gap-2 self-start rounded-full border border-zinc-300 bg-white px-5 py-2.5 text-sm font-semibold text-zinc-700 transition-all hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-800"
            >
                <RotateCcw className="h-4 w-4" />
                Analyze Another Leaf
            </button>
        </div>
    );
}